[package]
name        = "directories"
version     = "0.1.0"
authors     = [ "Simon Ochsenreither <simon@ochsenreither.de>" ]
description = "A minimal library that provides the platform-specific location of configuration, cache etc. directories by leveraging the mechanisms defined by the XDG base directory and the XDG user directory specifications on Linux, the Known Folder API on Windows, and the Standard Directory rules on macOS."
license     = "MPL-2.0"
repository  = "https://github.com/soc/directories-rs"
keywords    = ["xdg", "basedir"]

[dependencies]
winapi = { version = "0.3", features = ["knownfolders", "objbase", "shlobj"] }
