[package]
name    = "directories"
version = "0.0.1"
authors = [ "Simon Ochsenreither <simon@ochsenreither.de>" ]

[dependencies]
winapi = { version = "0.3", features = ["knownfolders", "objbase", "shlobj"] }
