[package]
name        = "directories"
version     = "0.5.0"
authors     = [ "Simon Ochsenreither <simon@ochsenreither.de>" ]
description = "A tiny library that provides platform-specific standard locations of directories for config, cache, etc. data on Linux, Windows and macOS by leveraging the mechanisms defined by the XDG base directory and the XDG user directory specifications on Linux, the Known Folder system on Windows, and the Standard Directory rules on macOS."
readme      = "README.md"
license     = "MPL-2.0"
repository  = "https://github.com/soc/directories-rs"
maintenance = { status = "actively-developed" }
keywords    = ["xdg", "basedir"]

[dependencies]
winapi = { version = "0.3", features = ["knownfolders", "objbase", "shlobj"] }
